[defines]
"target_os = ios" = "TARGET_OS_IOS"
"target_os = macos" = "TARGET_OS_MACOS"
"target_os = android" = "TARGET_OS_ANDROID"
"target_os = windows" = "TARGET_OS_WINDOWS"
"target_os = linux" = "TARGET_OS_LINUX"

[export]
prefix = "RCP"
include = ["RcpResult", "RcpError", "AppInfo", "User"]

[export.rename]
"RcpResult" = "RcpResult"
"RcpError" = "RcpError"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"
