#!/bin/bash
# Setup script for CI environments
set -e

echo "Setting up CI environment..."

# Install required Rust targets
echo "Installing required Rust targets..."
if [[ "$OSTYPE" == "darwin"* ]]; then
    # For macOS builds, we need these targets
    rustup target add x86_64-apple-darwin aarch64-apple-darwin
    # For iOS builds, these targets are needed
    rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # For Linux and cross-compiling to Windows
    rustup target add x86_64-unknown-linux-gnu
    rustup target add x86_64-pc-windows-gnu
elif [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "win32" ]]; then
    # For Windows native builds
    rustup target add x86_64-pc-windows-msvc
fi

# Skip code signing when running in CI
echo "Configuring build for CI environment..."
if [ ! -z "$CI" ] || [ ! -z "$GITHUB_ACTIONS" ]; then
    echo "CI environment detected, configuring code signing..."
    
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # Create directories for Flutter ephemeral files
        mkdir -p ./macos/Flutter/ephemeral
        
        # Add configuration to disable code signing in CI
        cat > ./macos/Flutter/ephemeral/Flutter-Generated.xcconfig << EOF
// Generated by CI setup script
#include "../Flutter-Debug.xcconfig"
#include "../ci-signing-override.xcconfig"

FLUTTER_ROOT=${FLUTTER_ROOT}
FLUTTER_APPLICATION_PATH=${PWD}
COCOAPODS_PARALLEL_CODE_SIGN=true
FLUTTER_BUILD_DIR=build
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1

CODE_SIGNING_ALLOWED=NO
CODE_SIGNING_REQUIRED=NO
CODE_SIGN_IDENTITY=-
EOF
        
        # Configure Podfile to skip code signing validation
        if [ -f "./macos/Podfile" ]; then
            echo "Updating Podfile to skip code signing validation..."
            sed -i '' 's/platform :osx.*/platform :osx, '\''10.14'\''\n\ninstall! '\''cocoapods'\'', :disable_input_output_paths => true/' ./macos/Podfile
            sed -i '' '/post_install/,/end/{s/target.build_configurations.each do |config|/target.build_configurations.each do |config|\n      config.build_settings['\''CODE_SIGNING_ALLOWED'\''] = '\''NO'\''\n      config.build_settings['\''CODE_SIGNING_REQUIRED'\''] = '\''NO'\''\n      config.build_settings['\''CODE_SIGN_IDENTITY'\''] = '\''-'\''/}' ./macos/Podfile
        fi
    fi
fi

echo "CI environment setup complete"
